# Generated by Django 5.2.14 on 2026-05-24 16:57

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0002_alter_catalogitem_default_unit_price_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotelineitem",
            name="quantity",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.00"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AddConstraint(
            model_name="client",
            constraint=models.UniqueConstraint(
                condition=models.Q(("email", ""), _negated=True),
                fields=("owner", "email"),
                name="unique_client_email_per_owner",
            ),
        ),
    ]
