# Generated by Django 5.2.14 on 2026-05-25 19:57
""" Alter migrations for the quotes app """

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0003_alter_quotelineitem_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyprofile",
            name="default_validity_days",
            field=models.PositiveIntegerField(
                default=30, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
